### ISSUE TITLE
Call to IpamVlanGroupsRead fails

### ISSUE THREAD

**Issue by joeyberkovitz** [netbox-community/go-netbox#134]
The Swagger definition for the Scope field in a VLAN group is listed as a string, although it can be an object as well. Example:
```
"scope": {
    "id": 1,
    "url": "http://netbox/api/dcim/sites/1/",
    "display": "TEST Site",
    "name": "TEST Site",
    "slug": "test"
},
```

When this happens, the API call fails with an unmarshaling error.

**Comment by v0ctor** [comment]
As the library is automatically generated from the Netbox OpenAPI specification, specification-related issues should be created in the [Netbox project](https://github.com/netbox-community/netbox/issues).

Anyway, this issue seems to be fixed in [the current specification](https://github.com/netbox-community/go-netbox/blob/master/api/openapi.json#L92679) (see line 92679).
