### ISSUE TITLE
Add option to find device by serial

### ISSUE THREAD

**Issue by andrewrynhard** [netbox-community/go-netbox#7]
It would be nice to be able to find a device by its' serial.

**Comment by mdlayher** [comment]
Hello!  Since NetBox is going to have API 2.0 in the near future, my plan was to more or less "freeze" the existing code and then focus effort in that area when it arrives.

In the mean time, would it help if I exported `Client.newRequest` and `Client.do` so you could perform the query you need outside this package?

**Comment by andrewrynhard** [comment]
@mdlayher That would be great. Do you know when 2.0 will be released?

**Comment by mdlayher** [comment]
I can do that. I don't have any info, but I suggest you check out the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) as they'll be the first ones to know.

**Comment by mdlayher** [comment]
Just merged #8 so you should be able to construct the query you need by making some type that implements `netbox.Valuer` and making a request with it.  Hope this helps.

I'll keep this open in case it's relevant for API 2.0.

**Comment by andrewrynhard** [comment]
Great, appreciate it!
